### ISSUE TITLE
BDD | Nuevas tablas descriptivas para reservaciones

### ISSUE THREAD

**Issue by omicto** [omicto/planificateur#9]
Se requieren tres nuevas tablas descriptivas para reservaciones.

Pendientes.
Pagadas.
Canceladas

Además de una tabla descriptora de las razones de cancelación

**Comment by curais** [comment]
ALTER TABLE CLIENTES MODIFY (cliente_desde null);
ALTER TABLE CLIENTES MODIFY (cliente_desde DEFAULT SYSDATE);
